package main

import (
	"fmt"

	"github.com/codahale/chacha20poly1305"
)

func readSecretKey(i int) []byte {
	return make([]byte, i)
}

func readRandomNonce(i int) []byte {
	return make([]byte, i)
}

func main() {
	key := readSecretKey(chacha20poly1305.KeySize) // must be 256 bits long

	c, err := chacha20poly1305.New(key)
	if err != nil {
		panic(err)
	}

	nonce := readRandomNonce(c.NonceSize()) // must be generated by crypto/rand
	plaintext := []byte("yay for me")
	data := []byte("whoah yeah")
	ciphertext := c.Seal(nil, nonce, plaintext, data)

	fmt.Printf("%x\n", ciphertext)
}
